# Generated by Django 4.0.3 on 2022-04-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.CharField(default='anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
